### ISSUE TITLE
[BUG] - Price Analysis

### ISSUE THREAD

**Issue by foxpcteam** [Super-Chain/AI-Marketer#4]
Hi,

I check your demo site and inside "Price Analysis" i have play with some countries, when I change to "RU" or "IL" I got error:

```
Error :( Please check your input again !
```

**Comment by catyung** [comment]
Hello , 

I just tested it again ! 

RU & IL should works : 

<img width="825" alt="螢幕擷取畫面 2022-04-26 185918" src="https://user-images.githubusercontent.com/49334769/165285829-055c1b83-6bd5-4775-809b-439e3f875d82.png">
<img width="848" alt="螢幕擷取畫面 2022-04-26 185944" src="https://user-images.githubusercontent.com/49334769/165285839-43e6121a-f14f-4ccb-a510-9793d9a8456e.png">

**Comment by catyung** [comment]
I found the bug ! Based on differnet currency format, the pricing struture is different, now i changed the format_price funciton, tested "RU" and "IL" also looks fine!!! thanks for report !

Just push the updated version of priceanalysis.py
